
project_id = "ruanewybqxrdfvrdyeqr"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[functions]
[functions.create-user]
verify_jwt = true

[functions.clock-in]
enabled = true
verify_jwt = true
import_map = "./functions/clock-in/deno.json"
entrypoint = "./functions/clock-in/index.ts"

[functions.clock-out]
enabled = true
verify_jwt = true
import_map = "./functions/clock-out/deno.json"
entrypoint = "./functions/clock-out/index.ts"

[functions.validate-member]
enabled = true
verify_jwt = false

[functions.backup-database]
enabled = true
verify_jwt = true
import_map = "./functions/backup-database/deno.json"
entrypoint = "./functions/backup-database/index.ts"
